// Generated by gencpp from file lidar_based_task1/ObstaclePose.msg
// DO NOT EDIT!


#ifndef LIDAR_BASED_TASK1_MESSAGE_OBSTACLEPOSE_H
#define LIDAR_BASED_TASK1_MESSAGE_OBSTACLEPOSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace lidar_based_task1
{
template <class ContainerAllocator>
struct ObstaclePose_
{
  typedef ObstaclePose_<ContainerAllocator> Type;

  ObstaclePose_()
    : header()
    , x(0.0)
    , y(0.0)
    , z(0.0)
    , r(0.0)  {
    }
  ObstaclePose_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , x(0.0)
    , y(0.0)
    , z(0.0)
    , r(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _z_type;
  _z_type z;

   typedef double _r_type;
  _r_type r;





  typedef boost::shared_ptr< ::lidar_based_task1::ObstaclePose_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lidar_based_task1::ObstaclePose_<ContainerAllocator> const> ConstPtr;

}; // struct ObstaclePose_

typedef ::lidar_based_task1::ObstaclePose_<std::allocator<void> > ObstaclePose;

typedef boost::shared_ptr< ::lidar_based_task1::ObstaclePose > ObstaclePosePtr;
typedef boost::shared_ptr< ::lidar_based_task1::ObstaclePose const> ObstaclePoseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lidar_based_task1::ObstaclePose_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lidar_based_task1::ObstaclePose_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace lidar_based_task1

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'lidar_based_task1': ['/home/nctuece/robotx_gazebo/catkin_ws/src/lidar_based_task1/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::lidar_based_task1::ObstaclePose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lidar_based_task1::ObstaclePose_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lidar_based_task1::ObstaclePose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lidar_based_task1::ObstaclePose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lidar_based_task1::ObstaclePose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lidar_based_task1::ObstaclePose_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lidar_based_task1::ObstaclePose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a99a9b2fb0c861a1fcea64c1942fd4cd";
  }

  static const char* value(const ::lidar_based_task1::ObstaclePose_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa99a9b2fb0c861a1ULL;
  static const uint64_t static_value2 = 0xfcea64c1942fd4cdULL;
};

template<class ContainerAllocator>
struct DataType< ::lidar_based_task1::ObstaclePose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lidar_based_task1/ObstaclePose";
  }

  static const char* value(const ::lidar_based_task1::ObstaclePose_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lidar_based_task1::ObstaclePose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 r\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::lidar_based_task1::ObstaclePose_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lidar_based_task1::ObstaclePose_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.r);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ObstaclePose_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lidar_based_task1::ObstaclePose_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lidar_based_task1::ObstaclePose_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
    s << indent << "r: ";
    Printer<double>::stream(s, indent + "  ", v.r);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LIDAR_BASED_TASK1_MESSAGE_OBSTACLEPOSE_H
