// Generated by gencpp from file lidar_based_task1/ObstaclePoseList.msg
// DO NOT EDIT!


#ifndef LIDAR_BASED_TASK1_MESSAGE_OBSTACLEPOSELIST_H
#define LIDAR_BASED_TASK1_MESSAGE_OBSTACLEPOSELIST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <lidar_based_task1/ObstaclePose.h>

namespace lidar_based_task1
{
template <class ContainerAllocator>
struct ObstaclePoseList_
{
  typedef ObstaclePoseList_<ContainerAllocator> Type;

  ObstaclePoseList_()
    : header()
    , list()
    , size(0)  {
    }
  ObstaclePoseList_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , list(_alloc)
    , size(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::lidar_based_task1::ObstaclePose_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::lidar_based_task1::ObstaclePose_<ContainerAllocator> >::other >  _list_type;
  _list_type list;

   typedef uint32_t _size_type;
  _size_type size;





  typedef boost::shared_ptr< ::lidar_based_task1::ObstaclePoseList_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lidar_based_task1::ObstaclePoseList_<ContainerAllocator> const> ConstPtr;

}; // struct ObstaclePoseList_

typedef ::lidar_based_task1::ObstaclePoseList_<std::allocator<void> > ObstaclePoseList;

typedef boost::shared_ptr< ::lidar_based_task1::ObstaclePoseList > ObstaclePoseListPtr;
typedef boost::shared_ptr< ::lidar_based_task1::ObstaclePoseList const> ObstaclePoseListConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lidar_based_task1::ObstaclePoseList_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lidar_based_task1::ObstaclePoseList_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace lidar_based_task1

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'lidar_based_task1': ['/home/nctuece/robotx_gazebo/catkin_ws/src/lidar_based_task1/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::lidar_based_task1::ObstaclePoseList_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lidar_based_task1::ObstaclePoseList_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lidar_based_task1::ObstaclePoseList_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lidar_based_task1::ObstaclePoseList_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lidar_based_task1::ObstaclePoseList_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lidar_based_task1::ObstaclePoseList_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lidar_based_task1::ObstaclePoseList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "03a580738d2edadd2ccd0ff18ab5984c";
  }

  static const char* value(const ::lidar_based_task1::ObstaclePoseList_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x03a580738d2edaddULL;
  static const uint64_t static_value2 = 0x2ccd0ff18ab5984cULL;
};

template<class ContainerAllocator>
struct DataType< ::lidar_based_task1::ObstaclePoseList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lidar_based_task1/ObstaclePoseList";
  }

  static const char* value(const ::lidar_based_task1::ObstaclePoseList_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lidar_based_task1::ObstaclePoseList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
lidar_based_task1/ObstaclePose[] list\n\
uint32 size\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: lidar_based_task1/ObstaclePose\n\
Header header\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 r\n\
";
  }

  static const char* value(const ::lidar_based_task1::ObstaclePoseList_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lidar_based_task1::ObstaclePoseList_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.list);
      stream.next(m.size);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ObstaclePoseList_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lidar_based_task1::ObstaclePoseList_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lidar_based_task1::ObstaclePoseList_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "list[]" << std::endl;
    for (size_t i = 0; i < v.list.size(); ++i)
    {
      s << indent << "  list[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::lidar_based_task1::ObstaclePose_<ContainerAllocator> >::stream(s, indent + "    ", v.list[i]);
    }
    s << indent << "size: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.size);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LIDAR_BASED_TASK1_MESSAGE_OBSTACLEPOSELIST_H
